name: mini_proje_uygulamasi

description: A new Flutter project

environment:
  sdk: '>=2.18.0 <4.0.0'  # SDK kısıtlaması eklendi

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.5.0  # firebase_auth için uyumlu sürüm
  cloud_firestore: ^5.5.0  # cloud_firestore için uyumlu sürüm
  js: ^0.7.2  # firebase_auth_web için gerekli olan js paketi
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
